/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergesort.java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MergeSortTest {

    @Test
    void mergeSortOneNumber() {
        int[] array = { 1 };
        int[] result = MergeSort.mergeSort(array);
        assertEquals(1, result[0]);

        int[] array2 = { 50 };
        int[] result2 = MergeSort.mergeSort(array2);
        assertEquals(50, result2[0]);
    }

    @Test
    void mergeSort() {
        int[] array = { 50, 1, 70, 48, 36, 96, 15, 3, 74, 100};
        int[] result = MergeSort.mergeSort(array);
        assertEquals(1, result[0]);
        assertEquals(3, result[1]);
        assertEquals(15, result[2]);
        assertEquals(36, result[3]);
        assertEquals(48, result[4]);
        assertEquals(50, result[5]);
        assertEquals(70, result[6]);
        assertEquals(74, result[7]);
        assertEquals(96, result[8]);
        assertEquals(100, result[9]);
    }
}
