/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergesort.java;

public class MergeSort {

    public static int[] mergeSort(int[] array) {
        if (array.length == 1) {
            return array;
        }

        // int[] array = { 50, 1, 70, 48, 36, 96, 15, 3, 74, 100};
        int left1 = array[0];
        int right1 = array[array.length/2-1];
        System.out.println("left:" + left1);
        System.out.println("right:" + right1);
        int[] l1 = { left1, right1 };

        int left2 = array[array.length/2];
        int right2 = array[array.length-1];
        System.out.println("left2:" + left2);
        System.out.println("right2:" + right2);
        int[] l2 = { left2, right2 };

//        System.out.println("left array" + l1.toString());
//        System.out.println("right array" + l2.toString());

        l1 = mergeSort(l1);
        l2 = mergeSort(l2);

        return array;
    }

    public static int[] mergeSort(int[] l1, int[] l2) {

        int[] result;

        while (l1.length > 0 && l2.length > 0) {
           if (l1[0] > l2[0]) {
               result.
           }
        }

        return array;
    }

    public static void main(String[] args) {
        System.out.println("");
    }
}